(ns klangmeister.actions)

(defrecord Play [target])
(defrecord PlayOnce [target])
(defrecord Doc [string target])
(defrecord Test [target])
(defrecord Gist [gist target])
(defrecord Import [uri target])
(defrecord Loop [target])
(defrecord Stop [target])
(defrecord Refresh [text target])
